<!-- This line outputs the doctype we set in the bootstrap -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>myCharityPie: One donation, many charities</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css') ?>
  <link type="text/css" href="http://ui.jquery.com/themes/base/ui.all.css" rel="stylesheet" />
  <?php print $this->headScript(); ?>
</head>

<body class="body-inline body-<?php print $this->placeholder('site-section'); ?>">

<div id="wrapper">
  <div id="inline">
    <?php echo $this->layout()->content ?>
  </div>
</div>

</body>
</html>
