<?php $this->placeholder('site-section')->set('causes'); ?>

<h3>Causes tagged as <?php print $this->tag['label']; ?></h3>

<?php if (count($this->paginator) == 0) { ?>

  <p>No causes found</p>

<?php } else { ?>
  <?php
  print $this->partial('causes/causes_listing.phtml',array('causes'=>$this->paginator));
  print $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('page_url'=>$this->page_url,'page_route'=>$this->page_route));
}

?>

