<?php echo $this->menu('causes'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>

	<div id="mainContent">
		<h3>Causes</h3>

<?php
foreach ($this->tags as $tag) {
  ?><a href="<?php print $this->url(array(
    'tagid'=>$tag['tag_id'],
    'page'=>1
  ),'browsecauses') ?>"><?php print $tag['label'] ?></a> (<?php print $tag['causes']?>) <?php
}
?>

	</div>
    <br class="clear" />
</div>