<?php echo $this->menu('charities'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>
    <?php $action_url = $this->url(array(),'charities',true); ?>
  <div id="sidebar">
        <h3>Search</h3>
        <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="search" />
            <input type="text" id="search" name="s" valuex="Enter keyword to sea
rch" onfocus="javascript:if (this.value=='Enter keyword to search') this.value='
';" onblur="javascript:if (this.value=='') this.value='Enter keyword to search';
" />
            <input type="submit" value="Search" />
        </form>
        <h3>Categories</h3>
       <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="select" />
            <select name="tag_id" id="category">            <?php
                foreach ($this->charity_tags as $tag) {
                    print('<option value="'.$tag['tag_id'].'">'.$tag['label'].' 
('.$tag['charities'].')</option>');
                }
            ?>
            </select>
            <input type="submit" value="Search" />
        </form>
    </div>

	<div id="mainContent">
		<h3>Causes</h3>

<?php
foreach ($this->causes as $cause) {
?>
  <a href="<?php print $this->url(array('causeid'=>$cause['cause_id']),'viewcause') ?>"><?php print $cause['title'] ?></a><br/>
<?php
//  print_r ($cause);
  print "<hr>";
}
?>
	</div>
    <br class="clear" />
</div>


