<?php echo $this->menu('causes'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>

<h3>Cause: <?php print $this->cause['title']?></h3>
<!-- created by $this->cause['user_id'] -->
<!-- Nth most popular cause on myCharityPie in the last XX days -->

<a href="<?php print $this->url(array('recipientType'=>'cause','recipientId'=>$this->cause["cause_id"]),'addslice',true) ?>">[ add to my pie ]</a>

<?php print $this->partial('pie\index.phtml',array('pie'=>$this->pie)); ?>

<?php if ($this->is_pie_owner) { ?>
<?php print $this->edit_form ?>
<?php } ?>
    <br class="clear" />
</div>


