<?php
$colors = explode(',',COLORS);
$colors = implode($colors,"','");
$colors = "'".$colors."'";
?>
{
  "bg_colour":"#f8f8ff",
  "elements":[
    {
      "type":      "pie",
      "colours":   [<?php print $colors ?>],
      "alpha":     0.6,
      "border":    1,
      "animate":   0,
      "start-angle": 35,
      "values" :   [
<?php
$i = 0;
foreach ($this->slices as $slice) {
  if ($i > 0) print ',';
  ?>{
    "value":<?php print $slice['percentage'] ?>,
    "id":"<?php print $slice['slice_id'] ?>"
    }<?php
  $i++;
}
?>
      ]
    }
  ]
}