<br clear="all"/>

<div id="contents" class="container_12">

<div class="grid_3">&nbsp;</div>
<div id="contents-main" class="grid_6">
<h1>Welcome to myCharityPie!</h1>
</div>
<div class="grid_3">&nbsp;</div>
<div id="contents-main" class="grid_4">
<h2><a href="/charities/">Charities</a></h2>
<p>browse, search, find your favourite</p>
</div>
<div id="contents-main" class="grid_4">
<h2><a href="/causes/">Causes</a></h2>
<p>Make your own cause of your favourite charities and share it with others.</p>
<p>Check out the causes made by others, you can even add them to your own pie. Why not check out <a href="/causes/123">Bob Geldof's PovertyPie</a> and <a href="/causes/234">Bono's RED </a>?</p>
</div>
<div id="contents-main" class="grid_4">
<h2><a href="/mypie/">My Pie</a></h2>
<p>Make changes to your own pie. See the latest news from your favourite charities. See who else has a pie similar to your own.</p>
</div>
</div>
