<?php echo $this->menu('charities'); ?>
<div id="contents" class="container_12">
    <div id="contents-sidebar" class="grid_3">
        <h3>Search</h3>
        <input type="text" id="search" name="s" value="Enter keyword to search" />
        <h3>Categories/Tags</h3>
        <select id="category" onchange="location.href = '/charities/category/' + value;">
            <option value="">Choose a category</option>
<?php foreach ($this->charity_categories as $category) : ?>
            <option value="<?php echo $category["category_id"] ?>"><?php echo $category["name"] ?></option>
<?php endforeach ?>
        </select>
    </div>
    <div id="contents-main" class="grid_9">
        <h2>Charities - <?php echo $this->category_info["name"] ?></h3>

		<dl>
<?php foreach ($this->charities as $charity) : ?>
            <dt><a href="/charities/<?php echo $charity["charity_id"]; ?>"><?php echo $charity["name"] ?></a></dt>
            <dd><?php echo $charity["description"] ?></dd>
            <dd><a href="/charities/<?php echo $charity["charity_id"]; ?>">[ More info ]</a> <a href="/mypie/add/charity/<?php echo $charity["charity_id"];?>">[ Add to My Pie ]</a></dd>
			<dd>&nbsp;</dd>
<?php endforeach ?>
		<dl>
    </div>

    <div class="clear">&nbsp;</div>
</div>
