<?php echo $this->menu('charities'); ?>

<div id="contents">

  <?php $this->searchsidebar(); ?>
    <?php $action_url = $this->url(array(),'charities',true); ?>
  <div id="sidebar">
        <h3>Search</h3>
        <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="search" />
            <input type="text" id="search" name="s" valuex="Enter keyword to sea
rch" onfocus="javascript:if (this.value=='Enter keyword to search') this.value='
';" onblur="javascript:if (this.value=='') this.value='Enter keyword to search';
" />
            <input type="submit" value="Search" />
        </form>
        <h3>Categories</h3>
        <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="select" />
            <select name="tag_id" id="category">            <?php
                foreach ($this->charity_tags as $tag) {
                    print('<option value="'.$tag['tag_id'].'">'.$tag['label'].' ('.$tag['charities'].')</option>');
                }
            ?>
            </select>
            <input type="submit" value="Search" />
        </form>
    </div>


	<div id="mainContent">
    	<h3>Charities</h3>
<?php if (!$this->charities) { ?>
<p>Please use the search box to the left to find your favourite charity or browse the list of charities.</p>
<p>Our list of charities is quite short while we're in development. We have secured access to the Charities Commission's database, so over time we will be moving the whole database online. In the meantime, if you want your favourite charity listed, please <a href="mailto:mycharitypie@yahoo.co.uk">email us</a>.</p>
<?php } else { ?>
		<p><?php print($this->list_title) ?></p>
		<?php
			foreach ($this->charities as $charity) {
				print('<p><a href="'.$this->url().'/'.$charity['charity_id'].'">'.$charity['name'].'</a><br />'.$charity['description'].'</p>');
			}
	  }
		?>
	</div>

    <br class="clear" />
</div>

