<?php echo $this->menu('charities'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>

	<div id="mainContent">
    	<h3>Charities</h3>
<?php if (!$this->charities) { ?>
<p>Please use the search box to the left to find your favourite charity or browse the list of charities.</p>
<p>Our list of charities is quite short while we're in development. We have secured access to the Charities Commission's database, so over time we will be moving the whole database online. In the meantime, if you want your favourite charity listed, please <a href="mailto:mycharitypie@yahoo.co.uk">email us</a>.</p>
<?php } else { ?>
		<p><?php print($this->list_title) ?></p>
		<?php
			foreach ($this->charities as $charity) {
				print('<p><a href="'.$this->url().'/'.$charity['charity_id'].'">'.$charity['name'].'</a><br />'.$charity['description'].'</p>');
			}
	  }
		?>
	</div>

    <br class="clear" />
</div>

