<?php $this->placeholder('site-section')->set('charities'); ?>

<?php echo $this->menu('charities'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>
    <?php $action_url = $this->url(array(),'charities',true); ?>

    <div id="mainContent">
        <h3><?php echo $this->charity["name"] ?></h3>

        <?php print $this->partial('pie\addtopie.phtml',array('type'=>'charity','id'=>$this->charity["charity_id"])); ?>

		<dl>
            <dt>Description</dt>
            <dd><?php echo $this->charity["description"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Website</dt>
            <dd><?php echo $this->charity["website"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Phone</dt>
            <dd><?php echo $this->charity["phone"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Address</dt>
            <dd><?php echo $this->charity["address"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Charities Commission registration number</dt>
            <dd><?php echo $this->charity["registration"] ?></dd>
			<dd>&nbsp;</dd>
			<dd></dd>
			<dd>... other stuff about finances, contacts etc ... </dd>
		<dl>
    </div>
    <br class="clear" />
</div>
