
    <div id="mainContent">
        <h3><?php echo $this->charity["name"] ?></h3>

		<dl>
            <dt>Description</dt>
            <dd><?php echo $this->charity["description"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Website</dt>
            <dd><?php echo $this->charity["website"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Phone</dt>
            <dd><?php echo $this->charity["phone"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Address</dt>
            <dd><?php echo $this->charity["address"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Charities Commission registration number</dt>
            <dd><?php echo $this->charity["registration"] ?></dd>
			<dd>&nbsp;</dd>
			<dd></dd>
			<dd>... other stuff about finances, contacts etc ... </dd>
			<dd><a href="<?php print $this->url(array('recipientType'=>'charity','recipientId'=>$this->charity["charity_id"]),'addslice',true) ?>">[ add to my pie ]</a></dd>
		<dl>
    </div>