<?php // login/index.phtml ?>
<div id="stylized" class="myform">
<h1>Please Login</h1>
<p>To create your own CharityPie or rate or comment on charities, you must login.</p>
<?php echo $this->form ?>
<div class="spacer">&nbsp;</div>
<div class="spacer">&nbsp;</div>
<p class="info" align="center">Don't have an account yet? <a href="/user/register/">Create an account</a><br />
Forgot your password? <a href="/user/resetpassword/">Have it re-sent</a></p>
</div>
