<?php // login/index.phtml ?>

<?php $this->placeholder('site-section')->set('registersuccess'); ?>

<div id="contents" class="myform">
<h3>Congratulations!</h3>
<p>You have just created an account on myCharityPie.com.</p>
<div class="spacer"></div>
<p>Now you can <a href="/charities">Browse the list of charities</a>, <a href="//causes">View causes</a>, or <a href="/mypie">Start making your own pie</a>!</p>
</div>
<div>
</div>
