<!-- This line outputs the doctype we set in the bootstrap -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>myCharityPie: One donation, many charities</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css') ?>
  <link type="text/css" href="http://ui.jquery.com/themes/base/ui.all.css" rel="stylesheet" />
  <?php print $this->headScript(); ?>
</head>

<body class="body-<?php print $this->placeholder('site-section'); ?>">

<div id="topbar">
    <div id="utilities">
        <div id="utility-links">
			<a href="<?php print $this->url(array('controller'=>'about','action'=>'index'),'default'); ?>">About</a> |
			<a href="http://blog.mycharitypie.com/">Blog</a>
		</div>
        <div id="utility-user">
			<?php echo $this->profileLink(); ?>
		</div>
        <br class="clear" />
    </div>
</div>

<div id="container">

<div id="header">
	<div id="logo">
		<p>
			<a href="<?php print $this->baseUrl(); ?>/" title="Back to Home"><img src="<?php print $this->baseUrl() ?>/img/logo.png" /></a>
		</p>
	</div>
	<div id="description">
		<h2>One donation, many charities</h2>
		<p>Find your favourite charities. Discover new charities.<br/>
See your friends' favourite charities.<br/>
Put them all together to make your own CharityPie.<br/>
Make a cause of your selected charities.<br/>
Share them with your friends!</p>
	</div>
</div>

	<?php echo $this->layout()->content ?>

<div id="footer">
	<p class="copyright">
    <?php
    $url_about   = $this->url(array('controller'=>'about','action'=>'index'),'default');
    $url_terms   = $this->url(array('controller'=>'about','action'=>'terms'),'default');
    $url_privacy = $this->url(array('controller'=>'about','action'=>'privacy'),'default');
    $url_contact = $this->url(array('controller'=>'about','action'=>'contact'),'default');
    ?>
		<a href="<?php print $url_about ?>">About</a> |
    <a href="<?php print $url_terms ?>">Terms &amp; Conditions</a> |
    <a href="<?php print $url_privacy ?>">Privacy policy</a> |
    <a href="<?php print $url_contact ?>">Contact Us</a>
	</p>
	<p class="copyright">&copy; 2009 myCharityPie. <a href="<?php echo $this->url(array('action'=>'terms','controller'=>'about'), 'default')?>">Charity Commission content used under licence.</a></p>
</div>
</body>
</html>
