<!-- This line outputs the doctype we set in the bootstrap -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>myCharityPie: many charities, one donation</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css') ?>
</head>
<body class="body-charities">

<div id="topbar">
    <div id="utilities">
        <div id="utility-links">
			<a href="/about/">About</a> |
			<a href="http://blog.mycharitypie.com/">Blog</a>
		</div>
        <div id="utility-user">
			<?php echo $this->profileLink(); ?>
		</div>
        <br class="clear" />
    </div>
</div>

<div id="container">

<div id="header">
	<div id="logo">
		<p>
			<a href="<?php print $this->baseUrl(); ?>/" title="Back to Home"><img src="<?php print $this->baseUrl() ?>/img/logo.jpg" /></a>
		</p>
	</div>
	<div id="description">
		<h2>One donation, many charities</h2>
		<p>Find your favourite charities. Discover new charities.<br/>
See your friends' favourite charities.<br/>
Put them all together to make your own CharityPie.<br/>
Make a cause of your selected charities.<br/>
Share them with your friends!</p>
	</div>
</div>

	<?php echo $this->layout()->content ?>

<div id="footer" class="grid_12">
	<p class="copyright">
		<a href="/about/">About</a> | <a href="/about/terms/">Terms &amp; Conditions</a> | <a href="/about/privacy/">Privacy policy</a> | <a href="/about/contact/">Contact Us</a>
	</p>
	<p class="copyright">&copy; 2009 myCharityPie</p>
</div>
</body>
</html>
