
<h2>My Pie</h3>
<p>You pie has <?php print $this->slices_count ?>/10 slices</p>
  <?php
  foreach ($this->pie_slices as $slice) {
    ?>
    <h3><?php print $slice['recipient_name'] ?></h3>
    <p><a href="<?php print $this->url(array('sliceid'=>$slice['slice_id']),'deleteslice') ?>">remove from MyPie</a>
    <?php
  }
  ?>
</div>

<h3>My Causes</h3>
<?php print $this->cause_form ?>

<div class="clear">&nbsp;</div>
