<?php $this->placeholder('site-section')->set('mypie'); ?>

<h2>My Pie</h3>

<!-- SYSTEM MESSAGES -->
<?php if (!empty($this->messages)) { ?>
  <h1><?php print_r ($this->messages) ?></h1>
<?php } ?>

<!-- DONATION INFO -->
<?php if ($this->user > 0) { ?>
<div class="donations">
  <?php if ($this->donation == null) { ?>
    I don't have a monthly donation amount set up.
    <?php print $this->donate_form; ?>
  <?php } else { ?>
    I'm currently donating £<?php print ($this->donation['amount']); ?> a month.
    <a class="thickbox" href="<?php print $this->url(array('controller'=>'mypie','action'=>'donate'),'default'); ?>?height=100&width=280">change</a>
  <?php } ?>
</div>
<?php } ?>

<!-- THE PIE -->
<?php print $this->partial('pie/index.phtml',array('pie'=>$this->pie)); ?>

