
<h2>My Pie</h3>
<p>You pie has <?php print $this->slices_count ?>/10 slices</p>
  <?php
  foreach ($this->pie_slices as $slice) {
    ?>
    <h3><?php print $slice['recipient_name'] ?></h3>
    <p><a href="<?php print $this->url(array('sliceid'=>$slice['slice_id']),'deleteslice') ?>">remove from MyPie</a>
    <?php
  }
  ?>
</div>

<?php if ($this->user()) { ?>
  <h3>My Causes</h3>
  <?php
  foreach ($this->causes as $cause) {
    ?><a href="<?php print $this->url(array('causeid'=>$cause['cause_id']),'viewcause',true) ?>"><?php print $cause['title'] ?></a><br/><?php
  }
  ?>
  <h3>New Cause:</h3>
  <?php
  print $this->cause_form;
}
?>

<div class="clear">&nbsp;</div>
