<?php echo $this->menu('causes'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>

	<div id="mainContent">
		<h3>Causes</h3>

<?php
foreach ($this->causes as $cause) {
?>
  <a href="<?php print $this->url(array('causeid'=>$cause['cause_id']),'viewcause') ?>"><?php print $cause['title'] ?></a><br/>
<?php
//  print_r ($cause);
  print "<hr>";
}
?>
	</div>
    <br class="clear" />
</div>