<br class="clear" />

<div id="contents">
<h1>About myCharityPie</h1>
 
<h2>Our Team</h2>
 
<p>myCharityPie gives people the power to share what's important to them and to donate to the people who can make a difference.</p>
<blockquote>"Changing the world one slice at a time"</blockquote>

 
<h3>Business &amp; Product Development</h3>
<p>Our business and product development team has produced the business model, flowchart of the site and all the business aspects of MyCharityPie.</p>
<ul class="teamMembers">
	<li>Carola Derpsch</li>
    <li>Owen Edwards</li>
    <li>Adam Morris</li>
    <li>Brendan Quinn</li>
    <li>Akshay Rangnekar</li>
    <li>Matt Rogers</li>
</ul>
 
<h3>Marketing</h3>
<p>Our Marketing team has been busy creating a blog, facebook group and a twitter account. They have planned a marketing strategy to promote and create awareness for our site.</p>
<ul class="teamMembers">
	<li>Simon Hall</li>
    <li>Rosanna Lau</li>
    <li>Sjors Timmer</li>
</ul>

<h3>Designers</h3>
<p>Our designers have come up not only with our graphics and designs but also have helped the other Launch48 teams.
<ul class="teamMembers">
    <li>Tony Wu</li>
    <li>Jeremy Wilken</li>
    <li>Baris Tosun</li>
    <li>Jesh Glinert</li>
</ul>

<h3>Developers</h3>
<p>Our developers have worked hard to set up the server, database and create the platform to make our pie-in-the-sky dream a reality!</p>
<ul class="teamMembers">
	<li>Nathan Sudell</li>
    <li>Miguel Florido</li>
    <li>David Gildeh</li>
    <li>Anthony Giwa</li>
    <li>Bob Gregory</li>
    <li>Wai Kien</li>
</ul>

</div>