<?php // login/index.phtml ?>

<?php $this->placeholder('site-section')->set('login'); ?>

<div id="contents" class="myform">
<h3>Please Login</h3>
<p>To create your own CharityPie or rate or comment on charities, you must login.</p>
<?php echo $this->form ?>
<div class="spacer">&nbsp;</div>
<div class="spacer">&nbsp;</div>
<p class="info" align="center">Don't have an account yet? <a href="<?php print $this->url(array('controller'=>'user','action'=>'register'),'default') ?>">Create an account</a><br />
Forgot your password? <a href="<?php print $this->url(array('controller'=>'user','action'=>'resetpassword'),'default') ?>">Have it re-sent</a></p>
</div>
