<?php // login/index.phtml ?>

<?php $this->placeholder('site-section')->set('register'); ?>

<div id="contents" class="myform">
<h3>Please Register</h3>
<p>To create your own CharityPie or rate or comment on charities, you must register.</p>
<?php echo $this->form ?>
<div class="spacer"></div>
</div>
<div>
<p>Already have an account? <a href="<?php print $this->url(array('controller'=>'user','action'=>'login'),'default') ?>">Just login</a></p>
<p>Forgot your password? <a href="<?php print $this->url(array('controller'=>'user','action'=>'forgotpassword'),'default') ?>">Have it re-sent</a></p>
</div>
