<?php // login/index.phtml ?>
<div id="stylized" class="myform">
<h1>Please Register</h1>
<p>To create your own CharityPie or rate or comment on charities, you must register.</p>
<?php echo $this->form ?>
<div class="spacer"></div>
</div>
<div>
<p>Already have an account? <a href="<?php print $this->url(array('controller'=>'user','action'=>'login'),'default') ?>">Just login</a></p>
<p>Forgot your password? <a href="<?php print $this->url(array('controller'=>'user','action'=>'forgotpassword'),'default') ?>">Have it re-sent</a></p>
</div>
