<!-- ?php echo $this->menu('charities'); ? -->
<br clear="all"/>
<div id="contents" class="container_12">
<h1>About myCharityPie</h1>
 
<p>My Charity Pie gives people the power to share what's important to them and to donate to the people who can make a difference.</p>

<p style="font-style: italic">"Changing the world one slice at a time"</p>
 
 
<h2>Our Team</h2>
 
<h3>Business & Product Development</h3>
 
<p>Our business and product development team has produced the business model, flowchart of the site and all the business aspects of MyCharityPie.</p>
 
<p>
Carola Derpsch<br />
Owen Edwards<br />
Adam Morris<br />
Brendan Quinn<br />
Akshay Rangnekar<br />
Matt Rogers
</p>
 
<h3>Marketing</h3>
 
<p>Our Marketing team has been busy creating a blog, facebook group and a twitter account.  They have planned a marketing strategy to promote and create awareness for our site.</p>
 
<p>
Simon Hall<br />
Rosanna Lau<br />
Sjors Timmer
</p>
 
<h3>Developers</h3>
 
<p>Our developers have worked hard to set up the server, database and create the platform to make our pie-in-the-sky dream a reality!</p>
 
<p>
Miguel Florido<br />
David Gildeh<br />
Anthony Giwa<br />
Bob Gregory<br />
Wai Kien<br />
Nathan Sudell
</p>
 
<h3>Designers</h3>
 
<p>Our designers have come up not only with our graphics and designs but also have helped the other Launch48 teams.
 
<p>
Anthony Giwa<br />
Jesh Glinert<br />
Jeremy Wilken<br />
</p>

</div>
