<?php $this->placeholder('site-section')->set('about'); ?>

<br class="clear" />
<div id="contents">
<h1>myCharityPie Usage Terms &amp; Conditions</h1>
<h2>Charity Commission Register of Charities data copyright notice</h2>
<p>&copy; Crown copyright and Crown database material is reproduced with the permission of the Controller
of HMSO and Queen's Printer for Scotland.</p>
<p>Granted under Value Added Licence V2009000102, dated 5 March 2009.</p>
<p>(Yes that's right, we got a licence from the Queen!)</p>
<h2>Copyright for all non-charity information</h2>
<p>All other content is Copyright (C) 2009 myCharityPie.</p>
<p>&nbsp;</p>
</div>
