<?php $this->placeholder('site-section')->set('charities'); ?>

<h3>Charities</h3>

<?php if (count($this->paginator) == 0) { ?>

  <p>Please use the search box to the left to find your favourite charity or browse the list of charities.</p>
  <p>Our list of charities is quite short while we're in development. We have secured access to the Charities Commission's database, so over time we will be moving the whole database online. In the meantime, if you want your favourite charity listed, please <a href="mailto:mycharitypie@yahoo.co.uk">email us</a>.</p>

  <hr/>

  <h3>Top Five Charities</h3>

  <?php
  print $this->partial('charities/charity_listing.phtml',array('charities'=>$this->charities,'hasCauses'=>$this->hasCauses));
  ?>
  
<?php } else { ?>

  <p><?php print($this->list_title) ?></p>
<?php
    print $this->partial('charities/charity_listing.phtml',array('charities'=>$this->paginator,'hasCauses'=>$this->hasCauses));
    print $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('page_url'=>$this->page_url,'page_route'=>$this->page_route));
}

?>