<?php echo $this->menu('charities'); ?>

<div id="contents">

  <?php $this->searchSidebar(); ?>
    <?php $action_url = $this->url(array(),'charities',true); ?>
  <div id="sidebar">
        <h3>Search</h3>
        <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="search" />
            <input type="text" id="search" name="s" valuex="Enter keyword to sea
rch" onfocus="javascript:if (this.value=='Enter keyword to search') this.value='
';" onblur="javascript:if (this.value=='') this.value='Enter keyword to search';
" />
            <input type="submit" value="Search" />
        </form>
        <h3>Categories</h3>
        <form method="post" action="<?php print $action_url ?>">
            <input type="hidden" name="listMethod" value="select" />
            <select name="tag_id" id="category">            <?php
                foreach ($this->charity_tags as $tag) {
                    print('<option value="'.$tag['tag_id'].'">'.$tag['label'].' ('.$tag['charities'].')</option>');
                }
            ?>
            </select>
            <input type="submit" value="Search" />
        </form>
    </div>

    <div id="mainContent">
        <h3><?php echo $this->charity["name"] ?></h3>

		<dl>
            <dt>Description</dt>
            <dd><?php echo $this->charity["description"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Website</dt>
            <dd><?php echo $this->charity["website"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Phone</dt>
            <dd><?php echo $this->charity["phone"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Address</dt>
            <dd><?php echo $this->charity["address"] ?></dd>
			<dd>&nbsp;</dd>
            <dt>Charities Commission registration number</dt>
            <dd><?php echo $this->charity["registration"] ?></dd>
			<dd>&nbsp;</dd>
			<dd></dd>
			<dd>... other stuff about finances, contacts etc ... </dd>
			<dd><a href="<?php print $this->url(array('recipientType'=>'charity','recipientId'=>$this->charity["charity_id"]),'addslice',true) ?>">[ add to my pie ]</a></dd>
		<dl>
    </div>
    <br class="clear" />
</div>
