<?php echo $this->menu('mypie'); ?>

<div id="contents">

<?php $this->searchSidebar(); ?>

<?php if (!empty($this->messages)) { ?>
<h1><?php print_r ($this->messages) ?></h1>
<?php } ?>

<h2>My Pie</h3>

<?php //$this->pie(); ?>

<?php if ($this->user()) { ?>
  <h3>My Causes</h3>
  <?php
  foreach ($this->causes as $cause) {
    ?><a href="<?php print $this->url(array('causeid'=>$cause['cause_id']),'viewcause',true) ?>"><?php print $cause['title'] ?></a><br/><?php
  }
  ?>
  <h3>New Cause:</h3>
  <?php
  print $this->cause_form;
}
?>

<div class="clear">&nbsp;</div>
    <br class="clear" />
</div>

